### ISSUE TITLE
Old NPM version

### ISSUE THREAD

**Issue by Primajin** [tjololo/npm-package-update-sync#8]
### Subject of the issue

Hey there, I really like this action, however it is creating gigantic changes due to the old npm version that is used under the hood.
Is it possible to use npm 7+ ?
Also the text is a bit odd when nothing was actually bumped.

--> see: https://github.com/Primajin/eyesbound/pull/57 `+1,070 −21,135`

Furthermore is it possible to use something like `uses: tjololo/npm-package-update-sync@latest` instead of pinning the version?

### Link to workflows 

https://github.com/Primajin/eyesbound/runs/3393969910?check_suite_focus=true

```
npm install package.json
  /usr/local/bin/npm install
  npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

### Steps to reproduce

1. use on a repo that uses a v2 package-lock.json as created by npm 7

Thanks and all the best

**Comment by tjololo** [comment]
I will try to make some tests with package-lock.json version 2 after work today :)

You have three options when it comes to version: 
* fixed version eg ```uses: tjololo/npm-package-update-sync@v1.0.3```
* get latest minor and patch version (^1): ```uses: tjololo/npm-package-update-sync@v1```
* latest version from main, this might be broken if I make a bad commit: ```uses: tjololo/npm-package-update-sync@main```

**Comment by Primajin** [comment]
Cool thank you very much!

**Comment by tjololo** [comment]
Hi again,
I had a go at making this action support nodejs v16 and npm v7 projects.
From v6 to v7 npm has change the exit code from npm outdated so the action did not think there was any updates.
This bug should be fixed in v1.1.0.

Example of how to use this in a project with npm 7 and package-lock version2:
```
name: Update npm dependencies

on:
  schedule:
    - cron: '0 8 * * 4'
 
jobs:
  npm_update_sync_node_16:
    runs-on: ubuntu-latest
    name: Update npm packages and sync package.json with nodejs 16 npm 7
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Update package.json
        id: update
        uses: tjololo/npm-package-update-sync@v1
        with:
          comment-updated: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "PR from integration tests package-lock v2"
          branch: "tests/npm-updates-integration-v2"
          body: ${{ steps.update.outputs.body }}
          labels: dependencies 
```

Note the step where I setup node version 16 before running my action.

Let me know if you run in to any problems :)
